name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2025 ]
    steps:
    - uses: actions/checkout@v5

    - name: Install rust stable
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.89.0
        components: rustfmt, clippy

    - uses: taiki-e/install-action@cargo-llvm-cov

    - name: Run cargo check
      run: cargo check

    - name: Run cargo fmt
      run: cargo fmt --all -- --check
    
    - name: Run cargo clippy
      run: cargo clippy --all-targets -- -D warnings

    - name: Run cargo build
      run: cargo build --all-targets

    - name: Run cargo test
      run: cargo test --all -- --nocapture

    - name: Run llvm-cov
      run: cargo llvm-cov --codecov --output-path codecov.json --include-build-script

    - name: Show cov summary
      run: cargo llvm-cov report --summary-only --include-build-script